const mongoose=require("mongoose")
const express=require("express")
const app=express()
const users=require("./routes/user.route")
const personal=require("./routes/personal.route")
const salary=require("./routes/salry")
const dotenv=require("dotenv")
const login=require("./login")
const verify=require("./verify")
dotenv.config()
app.use(express.json())

mongoose.connect("mongodb://localhost:27017/internalQ3").then(console.log("connected"))
app.use(verify)
app.use('/api',users)
app.use("/api",personal)
app.use("/api",salary)
app.use("/api",login)
app.listen("8000")